// Phase 51-03 (D-22): pins today's multi-page TIFF behaviour through the product adapter's
// own default arguments. -CommonIFD0= only clears IFD0 -- ExifTool refuses -IFD1:all= ("also
// deletes subsequent IFD's and possibly image data") -- so page two's four private tags are a
// known, measured limitation, not a bug this phase fixes. This test records that limitation as
// an explicit, falsifiable expectation rather than leaving it to be silently rediscovered.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { ExifToolAdapter } from "../../src/infrastructure/exiftool/exiftool_adapter";
import { ExiftoolProcess } from "../../src/infrastructure/exiftool/ExiftoolProcess";
import { assertDirEffect, snapshotDir } from "../helpers/dir_effect";
import {
	retainedPrivateTags,
	gpsKeys,
	findSentinels,
	readTiffGroupedTags,
	readSingleStrip,
	TIFF_PRIVATE_TAG_FLOOR,
} from "../helpers/tiff_probe";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.resolve(__dirname, "../e2e/fixtures/multipage.tif");
const EXIFTOOL_PATH =
	process.platform === "win32"
		? path.resolve(__dirname, "../../.resources/win/bin/exiftool.exe")
		: path.resolve(__dirname, "../../.resources/nix/bin/exiftool");

const ALL_SENTINELS = [
	"ZZP51-PAGE1-DESC",
	"ZZP51-PAGE1-SOFT",
	"ZZP51-PAGE1-ARTIST",
	"ZZP51-PAGE1-COPY",
	"ZZP51-PAGE2-DESC",
	"ZZP51-PAGE2-SOFT",
	"ZZP51-PAGE2-ARTIST",
	"ZZP51-PAGE2-COPY",
];
const PAGE_TWO_SENTINELS = [
	"ZZP51-PAGE2-DESC",
	"ZZP51-PAGE2-SOFT",
	"ZZP51-PAGE2-ARTIST",
	"ZZP51-PAGE2-COPY",
];

// This literal records a known limitation (D-22): only IFD0 is cleaned on a TIFF write,
// because ExifTool refuses to delete IFD1 wholesale ("also deletes subsequent IFD's and
// possibly image data"). It is hand-edited, never regenerated by a flag or a test run --
// changing it is a decision (expanding the fix to later TIFF pages), not a refresh. Measured
// against the product's own default arguments (-all= -CommonIFD0= -TagsFromFile @
// -Orientation -ICC_Profile) via the bundled 13.59 binary against a scratch copy of
// multipage.tif. IFD1:StripOffsets is excluded deliberately: ExifTool relocates it on
// rewrite (D-27), it is layout, not retained metadata.
const EXPECTED_IFD1_RETAINED_TODAY: Readonly<Record<string, unknown>> = {
	"IFD1:ImageWidth": 4,
	"IFD1:ImageHeight": 4,
	"IFD1:BitsPerSample": 8,
	"IFD1:Compression": "Uncompressed",
	"IFD1:PhotometricInterpretation": "BlackIsZero",
	"IFD1:ImageDescription": "ZZP51-PAGE2-DESC",
	"IFD1:SamplesPerPixel": 1,
	"IFD1:RowsPerStrip": 4,
	"IFD1:StripByteCounts": 16,
	"IFD1:XResolution": 72,
	"IFD1:YResolution": 72,
	"IFD1:ResolutionUnit": "inches",
	"IFD1:Software": "ZZP51-PAGE2-SOFT",
	"IFD1:Artist": "ZZP51-PAGE2-ARTIST",
	"IFD1:Copyright": "ZZP51-PAGE2-COPY",
};

describe("multi-page TIFF: only IFD0 is cleaned; IFD1 residue is pinned (D-22)", () => {
	const temporaryDirs: string[] = [];

	afterEach(() => {
		for (const dir of temporaryDirs.splice(0)) {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("the product's default arguments clean IFD0 and leave IFD1's private tags exactly as pinned", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "tiff-multipage-"));
		temporaryDirs.push(dir);
		const source = path.join(dir, "multipage.tif");
		fs.copyFileSync(FIXTURE, source);
		const destination = path.join(dir, "multipage-cleaned.tif");
		const before = snapshotDir(dir);

		const process = new ExiftoolProcess({ binPath: EXIFTOOL_PATH });
		const exiftool = new ExifToolAdapter({ process });
		await process.open();
		try {
			const result = await exiftool.sanitize({
				source,
				destination,
				outputMode: "copy",
				preserveOrientation: true,
				preserveColorProfile: true,
				preserveResolution: false,
				preserveTimestamps: false,
			});
			expect(result).toEqual({ ok: true, value: undefined });
		} finally {
			await process.close();
		}

		const after = snapshotDir(dir);
		assertDirEffect(before, after, {
			added: [path.basename(destination)],
			modified: [],
			removed: [],
			unchanged: ["multipage.tif"],
		});

		const tags = readTiffGroupedTags(destination, EXIFTOOL_PATH);

		expect(retainedPrivateTags(tags, "IFD0")).toEqual([]);
		expect(gpsKeys(tags)).toEqual([]);
		expect(retainedPrivateTags(tags, "IFD1")).toEqual(
			TIFF_PRIVATE_TAG_FLOOR.map((tag) => `IFD1:${tag}`),
		);

		const ifd1Actual: Record<string, unknown> = {};
		for (const [key, value] of Object.entries(tags)) {
			if (key.startsWith("IFD1:") && key !== "IFD1:StripOffsets") {
				ifd1Actual[key] = value;
			}
		}
		expect(ifd1Actual).toEqual(EXPECTED_IFD1_RETAINED_TODAY);

		expect(findSentinels(destination, ALL_SENTINELS)).toEqual(
			PAGE_TWO_SENTINELS,
		);

		const pristineIfd0Strip = readSingleStrip(FIXTURE, "IFD0", EXIFTOOL_PATH);
		const pristineIfd1Strip = readSingleStrip(FIXTURE, "IFD1", EXIFTOOL_PATH);
		const outputIfd0Strip = readSingleStrip(destination, "IFD0", EXIFTOOL_PATH);
		const outputIfd1Strip = readSingleStrip(destination, "IFD1", EXIFTOOL_PATH);
		expect(outputIfd0Strip.bytes.equals(pristineIfd0Strip.bytes)).toBe(true);
		expect(outputIfd1Strip.bytes.equals(pristineIfd1Strip.bytes)).toBe(true);
	});
});
